CREATE TABLE IF NOT EXISTS tasks(
    id SERIAL PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    text VARCHAR(100) NOT NULL, 
    time_add TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    is_done BOOLEAN NOT NULL,
    time_done TIMESTAMP
);