ALTER TABLE tasks ALTER COLUMN is_important DROP DEFAULT;
ALTER TABLE tasks ALTER COLUMN is_important TYPE BOOLEAN
USING CASE
    WHEN is_important IN(1, 2, 3) THEN TRUE ELSE FALSE
END;
ALTER TABLE tasks ALTER COLUMN is_important SET DEFAULT FALSE;